{{- if and .Values.minio.enabled (not .Values.minio.existingSecretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vexa.componentName" (list . "minio-credentials") }}
  labels:
    {{- include "vexa.labels" . | nindent 4 }}
type: Opaque
stringData:
  MINIO_ROOT_USER: {{ default (randAlphaNum 16) .Values.minio.auth.rootUser | quote }}
  MINIO_ROOT_PASSWORD: {{ default (randAlphaNum 32) .Values.minio.auth.rootPassword | quote }}
{{- end }}
